version: '3.9'
name : php82_mysql8
services:

    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        networks:
            - server
        volumes:
            - ../project:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php82-service
            - mysql8-service
        ports:
            - "8080:80"
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80

    php82-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php82-container
        ports:
            - "9000:9000"
        volumes:
            - ../project:/var/www/project
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - server


    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "4306:3306"
        volumes:
            - database:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - server

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin-container
        restart: always
        ports:
            - "8800:80"
        networks:
            - server
        environment:
            - PMA_HOST=mysql8-service


networks:
    server:
volumes:
    database:
        external: true
        name: database
